export { substringIncludes } from './helpers/substringIncludes'
export { useCustomState } from './hooks/useCustomState'
export { useLocalStorage } from './hooks/useLocalStorage'
export { default as examples } from './productExample/products.json'
export { clickScanner } from './helpers/windowScanner'